"""empty message

Revision ID: 6f680db4975a
Revises: e04b0d1d420d
Create Date: 2018-09-26 19:06:08.621597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f680db4975a'
down_revision = 'e04b0d1d420d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_destinacija_naziv', table_name='destinacija')
    op.create_index(op.f('ix_destinacija_naziv'), 'destinacija', ['naziv'], unique=False)
    op.drop_index('ix_destinacija_opis', table_name='destinacija')
    op.create_index(op.f('ix_destinacija_opis'), 'destinacija', ['opis'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_destinacija_opis'), table_name='destinacija')
    op.create_index('ix_destinacija_opis', 'destinacija', ['opis'], unique=1)
    op.drop_index(op.f('ix_destinacija_naziv'), table_name='destinacija')
    op.create_index('ix_destinacija_naziv', 'destinacija', ['naziv'], unique=1)
    # ### end Alembic commands ###
