"""empty message

Revision ID: 7a8fcc9ace6a
Revises: 
Create Date: 2018-09-17 20:07:04.835422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8fcc9ace6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_token_email'), 'api_token', ['email'], unique=True)
    op.create_index(op.f('ix_api_token_token'), 'api_token', ['token'], unique=True)
    op.create_table('kontinent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=64), nullable=True),
    sa.Column('slika_URL', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kontinent_naziv'), 'kontinent', ['naziv'], unique=True)
    op.create_index(op.f('ix_kontinent_slika_URL'), 'kontinent', ['slika_URL'], unique=True)
    op.create_table('drzava',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=64), nullable=True),
    sa.Column('slika_URL', sa.String(length=250), nullable=True),
    sa.Column('opis', sa.String(length=250), nullable=True),
    sa.Column('id_kontinent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_kontinent'], ['kontinent.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_kontinent')
    )
    op.create_index(op.f('ix_drzava_naziv'), 'drzava', ['naziv'], unique=True)
    op.create_index(op.f('ix_drzava_opis'), 'drzava', ['opis'], unique=True)
    op.create_index(op.f('ix_drzava_slika_URL'), 'drzava', ['slika_URL'], unique=True)
    op.create_table('destinacija',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=64), nullable=True),
    sa.Column('opis', sa.String(length=600), nullable=True),
    sa.Column('zvezdice', sa.Integer(), nullable=True),
    sa.Column('cena_smestaj', sa.Integer(), nullable=True),
    sa.Column('cena_avion', sa.Integer(), nullable=True),
    sa.Column('cena_bus', sa.Integer(), nullable=True),
    sa.Column('last_min', sa.Boolean(), nullable=True),
    sa.Column('id_drzava', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_drzava'], ['drzava.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinacija_naziv'), 'destinacija', ['naziv'], unique=True)
    op.create_index(op.f('ix_destinacija_opis'), 'destinacija', ['opis'], unique=True)
    op.create_index(op.f('ix_destinacija_zvezdice'), 'destinacija', ['zvezdice'], unique=False)
    op.create_table('aranzman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_destinacija', sa.Integer(), nullable=False),
    sa.Column('dat_pol', sa.DateTime(), nullable=True),
    sa.Column('dat_dol', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_destinacija'], ['destinacija.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_destinacija')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aranzman')
    op.drop_index(op.f('ix_destinacija_zvezdice'), table_name='destinacija')
    op.drop_index(op.f('ix_destinacija_opis'), table_name='destinacija')
    op.drop_index(op.f('ix_destinacija_naziv'), table_name='destinacija')
    op.drop_table('destinacija')
    op.drop_index(op.f('ix_drzava_slika_URL'), table_name='drzava')
    op.drop_index(op.f('ix_drzava_opis'), table_name='drzava')
    op.drop_index(op.f('ix_drzava_naziv'), table_name='drzava')
    op.drop_table('drzava')
    op.drop_index(op.f('ix_kontinent_slika_URL'), table_name='kontinent')
    op.drop_index(op.f('ix_kontinent_naziv'), table_name='kontinent')
    op.drop_table('kontinent')
    op.drop_index(op.f('ix_api_token_token'), table_name='api_token')
    op.drop_index(op.f('ix_api_token_email'), table_name='api_token')
    op.drop_table('api_token')
    # ### end Alembic commands ###
