"""empty message

Revision ID: 8da4cbe26782
Revises: 886d82f1a43a
Create Date: 2018-09-22 12:08:07.025000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da4cbe26782'
down_revision = '886d82f1a43a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinacija', sa.Column('lajkovi', sa.Integer(), nullable=True))
    op.add_column('destinacija', sa.Column('omiljeno', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinacija', 'omiljeno')
    op.drop_column('destinacija', 'lajkovi')
    # ### end Alembic commands ###
