"""empty message

Revision ID: 8e44d767e4ac
Revises: fb77cd52b666
Create Date: 2018-09-23 11:40:09.570000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e44d767e4ac'
down_revision = 'fb77cd52b666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinacija', sa.Column('slika_URL', sa.String(length=255), nullable=True))
    op.drop_index('ix_drzava_slika_URL', table_name='drzava')
    op.create_index(op.f('ix_drzava_slika_URL'), 'drzava', ['slika_URL'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drzava_slika_URL'), table_name='drzava')
    op.create_index('ix_drzava_slika_URL', 'drzava', ['slika_URL'], unique=1)
    op.drop_column('destinacija', 'slika_URL')
    # ### end Alembic commands ###
