"""empty message

Revision ID: fb77cd52b666
Revises: 8da4cbe26782
Create Date: 2018-09-22 12:33:39.205000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb77cd52b666'
down_revision = '8da4cbe26782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinacija', sa.Column('url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinacija', 'url')
    # ### end Alembic commands ###
